services:
    redis-cluster:
        image: docker.io/bitnami/redis-cluster:8.2.1-debian-12-r0
        command:
            - /bin/bash
            - -c
            - |
              # Backwards compatibility change
              if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
                  echo COPYING FILE
                  cp  /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
              fi
              pod_index=($(echo "$POD_NAME" | tr "-" "\n"))
              pod_index="${pod_index[-1]}"
              if [[ "$pod_index" == "0" ]]; then
                export REDIS_CLUSTER_CREATOR="yes"
                export REDIS_CLUSTER_REPLICAS="1"
                export REDISCLI_AUTH=`cat $REDIS_PASSWORD_FILE`
              fi
              /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
        environment:
            REDIS_AOF_ENABLED: "yes"
            REDIS_NODES: 'redis-cluster-0.redis-cluster-headless redis-cluster-1.redis-cluster-headless redis-cluster-2.redis-cluster-headless redis-cluster-3.redis-cluster-headless redis-cluster-4.redis-cluster-headless redis-cluster-5.redis-cluster-headless '
            REDIS_PASSWORD_FILE: /opt/bitnami/redis/secrets/redis-password
            REDIS_PORT_NUMBER: "6379"
            REDIS_TLS_ENABLED: "no"
        restart: unless-stopped
        network_mode: host
networks: {}
