baseURL = "https://compose.ashupednekar.github.io/"
languageCode = "en-us"
title = "Compose Documentation"
theme = "lotusdocs"

# Build into ../public so we can commit it as gh-pages
publishDir = "../public"

# Optional: make URLs absolute
canonifyURLs = true

