name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.150.1'
          extended: true

      - name: Build Hugo site
        working-directory: docs
        run: hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/public
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Deploy Hugo site"
          user_name: "GitHub Actions"
          user_email: "actions@github.com"
          enable_jekyll: false

